// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcQ6Pchg3o5eyMO1SnGepCMjIgCjloU2s',
    appId: '1:257261136629:android:495bff85889f4d2cd773bc',
    messagingSenderId: '257261136629',
    projectId: 'tarot-b38cc',
    databaseURL: 'https://tarot-b38cc-default-rtdb.firebaseio.com',
    storageBucket: 'tarot-b38cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO737-4vvI92C_UQqF-GZUXDqATSc--hA',
    appId: '1:257261136629:ios:5dcdc100fe776376d773bc',
    messagingSenderId: '257261136629',
    projectId: 'tarot-b38cc',
    databaseURL: 'https://tarot-b38cc-default-rtdb.firebaseio.com',
    storageBucket: 'tarot-b38cc.appspot.com',
    iosClientId: '257261136629-vb7tvds33eqhh5tn15u9qpbnlvoov76v.apps.googleusercontent.com',
    iosBundleId: 'com.example.tarotApp',
  );
}
